// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKhbHZCbe9RLKs3K69UyIvSYoA_Hg_580',
    appId: '1:472258498841:web:47c6ff3692ddaa6f20b588',
    messagingSenderId: '472258498841',
    projectId: 'driverapp-e91d5',
    authDomain: 'driverapp-e91d5.firebaseapp.com',
    storageBucket: 'driverapp-e91d5.appspot.com',
    measurementId: 'G-B49M87N0KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG2mQGFkWTzxfkVig-CRyjYXNGfeI0nag',
    appId: '1:472258498841:android:76f167b0495793a320b588',
    messagingSenderId: '472258498841',
    projectId: 'driverapp-e91d5',
    storageBucket: 'driverapp-e91d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwNd4rBDMC44bZy7H5FTt5LVI0LEInqto',
    appId: '1:472258498841:ios:b605ed5a1e51488420b588',
    messagingSenderId: '472258498841',
    projectId: 'driverapp-e91d5',
    storageBucket: 'driverapp-e91d5.appspot.com',
    iosBundleId: 'com.dvmpractice.praticetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwNd4rBDMC44bZy7H5FTt5LVI0LEInqto',
    appId: '1:472258498841:ios:b605ed5a1e51488420b588',
    messagingSenderId: '472258498841',
    projectId: 'driverapp-e91d5',
    storageBucket: 'driverapp-e91d5.appspot.com',
    iosBundleId: 'com.dvmpractice.praticetest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKhbHZCbe9RLKs3K69UyIvSYoA_Hg_580',
    appId: '1:472258498841:web:feb0c3181c46dbdb20b588',
    messagingSenderId: '472258498841',
    projectId: 'driverapp-e91d5',
    authDomain: 'driverapp-e91d5.firebaseapp.com',
    storageBucket: 'driverapp-e91d5.appspot.com',
    measurementId: 'G-4Y9X68716B',
  );
}
